# Generated by Django 4.0 on 2021-12-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('supplier_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sup', to='printingfac.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date_of_order', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('tax', models.CharField(max_length=7)),
                ('tax_amount', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='printingfac.customer')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='printingfac.material')),
                ('supplier_to_associate_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sta', to='printingfac.supplier')),
            ],
        ),
    ]
