# Generated by Django 4.0 on 2021-12-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printingfac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('emp_fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efac', to='printingfac.factory')),
                ('emp_sup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esup', to='printingfac.supplier')),
            ],
        ),
    ]
