# Generated by Django 4.0 on 2021-12-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printingfac', '0002_alter_factory_name_alter_material_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=30)),
                ('ph_no', models.IntegerField()),
                ('issues', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
